README.md
setup_grammar.py

Add readme, modify setup_grammar.py to show proper usage.

---

README.md

Add specific steps on how to build locally.

---

.github/dependabot.yml
.github/workflows/javascript.yml
.github/workflows/python.yml
cratedb_sqlparse_js/package-lock.json
cratedb_sqlparse_js/package.json
cratedb_sqlparse_py/tests/conftest.py
pyproject.toml
setup_grammar.py

What the title says. Accompanying the other corresponding patch about Python.
- GH-10

JavaScript: Add CI configuration for software tests and Dependabot

---

CHANGES.md
cratedb_sqlparse_js/cratedb_sqlparse/index.js
cratedb_sqlparse_py/cratedb_sqlparse/__init__.py
setup_grammar.py

In the build script, replace the old version with the new one rather than just appending the variable again, otherwise if you run the script several times you'd get the variable multiple times.

Replace the version on the target index_files rather instead of appending

---

cratedb_sqlparse_js/package-lock.json
cratedb_sqlparse_js/package.json
cratedb_sqlparse_js/vite.config.js

- The package intends to be published as `@cratedb/cratedb-sqlparse`.
- The package entrypoint was wrong, so `npm run build` croaked.

JavaScript: Fix package entrypoint. Naming things.

---

cratedb_sqlparse_js/package-lock.json
cratedb_sqlparse_js/package.json

A few more adjustments to `package.json` before upload, following up on GH-24.
I derived a few of those adjustments from the [`package.json` file of crate-gc-admin](https://github.com/crate/crate-gc-admin/blob/master/package.json). @alexdametto: Do you have any other suggestions? / Does it look sane?

JavaScript: Update project metadata file `package.json` before upload

---

cratedb_sqlparse_py/README.md
cratedb_sqlparse_py/cratedb_sqlparse/parser.py
cratedb_sqlparse_py/pyproject.toml
cratedb_sqlparse_py/tests/test_exceptions.py
cratedb_sqlparse_py/tests/test_lexer.py

Issue #2
This is one of the first pieces required to finish the feature and its only implemented in Python for early feedback/validation. 
Main changes of PR:
- Throwing antlr4 parse errors as exceptions is now only enabled by `raise_exception` API influenced by [DRF Validators](https://www.django-rest-framework.org/api-guide/exceptions/#validationerror)
- Default behaviour is not to raise an exception, the reason is that it forces clients to try/catch errors, when you already work with CrateDB in the HTTP protocol you are used to check the json response, rather than catching exceptions, this change of behaviour aims to make integrating with this library as similar as possible as with CrateDB.
- Implements an `ExceptionCollectorListener` that collects all errors that are caught, (remember …

Change error handling strategy and add verbose errors

---

cratedb_sqlparse_py/cratedb_sqlparse/parser.py
cratedb_sqlparse_py/tests/test_exceptions.py

Found an fixed an edge case where error was not being assigned to statement.

Improve heuristics of assigning an error to its statement

---

cratedb_sqlparse_py/README.md
cratedb_sqlparse_py/cratedb_sqlparse/AstBuilder.py
cratedb_sqlparse_py/cratedb_sqlparse/parser.py
cratedb_sqlparse_py/tests/test_enricher.py
setup_grammar.py

Implements extracting metadata using an `AstBuilder` to enrich a `Statement`
Currently only gets the schema and table name.
Example:
```python
stmt = sqlparse("SELECT A, B FROM doc.tbl1")[0]
print(stmt.metadata)
```
Sets the foundation for more features in the future, like #31 .

Extract metadata from the query into the statement.

---

cratedb_sqlparse_py/README.md
cratedb_sqlparse_py/cratedb_sqlparse/AstBuilder.py
cratedb_sqlparse_py/cratedb_sqlparse/parser.py
cratedb_sqlparse_py/pyproject.toml
cratedb_sqlparse_py/tests/test_enricher.py

This PR allows for extracting properties defined by `[ WITH ( parameter [= value] [, ... ] ) ]` statements.
For example:
```python
from cratedb_sqlparse import sqlparse
stmt = sqlparse("""
CREATE TABLE doc.tbl12 (A TEXT) WITH (
"allocation.max_retries" = 5,
"blocks.metadata" = false
);
""")[0]
print(stmt.metadata)
```
It also handles the special case of what I call, `interpolated values` and #31 if you have a better name recommendation, please go ahead :P

Add `with_properties` and `interpolated_properties`

---

.github/workflows/release.yml
DEVELOP.md
README.md

A release workflow for staging the Python package through GHA to PyPI.
Along the lines, the patch includes "developer guide" documentation for both Python and JavaScript.

CI: Add release workflow for staging the Python package through GHA to PyPI

---

cratedb_sqlparse_py/pyproject.toml

Currently the generated version is not accepted by pypi
From __https://peps.python.org/pep-0440/__:
Local version identifiers SHOULD NOT be used when publishing upstream projects to a public index server, but MAY be used to identify private builds created directly from the project source. Local version identifiers

Add valid pypi versioningit's version scheme

---

cratedb_sqlparse_py/pyproject.toml

cratedb-sqlparse requires Python `<3.13,>=3.8`
If you create a new environment with poetry for example, the default version will be `^{yoursystempythonversion}`, for my system which uses 3.12 is `^3.12`, this translates to `>=3.13,<4.0`.
Making it incompatible if I don't change my local version.
This is the error:
I checked how other popular packages define versions and most just do: `>=3.8` or `>=3.9` they don't bother with upper bounds, settings this fixes my issue.
example: https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/setup.py#L97C5-L97C28

Python: Set python version to just >=3.8

---

cratedb_sqlparse_js/package.json

I got this error while integrating this library in `crate-gc-admin`:
```
Could not find a declaration file for module '@cratedb/cratedb-sqlparse'.
'crate-gc-admin/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js' implicitly has an 'any' type.
There are types at 'crate-gc-admin/node_modules/@cratedb/cratedb-sqlparse/dist/index.d.ts', 
but this result could not be resolved when respecting package.json "exports". 
The '@cratedb/cratedb-sqlparse' library may need to update its package.json or typings.
```
Basically, for react with typescript projects, the [export](https://github.com/crate/cratedb-sqlparse/blob/main/cratedb_sqlparse_js/package.json#L36) in the `package.json` is "explicit", so even if types are declared [here](https://github.com/crate/cratedb-sqlparse/blob/main/cratedb_sq …

Javascript: Fixing type declaration on export in package.json

---

cratedb_sqlparse_js/cratedb_sqlparse/parser.js
cratedb_sqlparse_py/cratedb_sqlparse/parser.py

When there is only one parsed statement, just assign the error to the statement (it only takes the first one from .pop, if there are more it's ignored as currently our Statment object only has ONE possible error)

Match error singlestmt

---

cratedb_sqlparse_js/cratedb_sqlparse/generated_parser/SqlBaseParserListener.js
cratedb_sqlparse_js/cratedb_sqlparse/generated_parser/SqlBaseParserVisitor.js
cratedb_sqlparse_js/cratedb_sqlparse/index.js
cratedb_sqlparse_py/cratedb_sqlparse/__init__.py

Set CrateDB version to 5.7.5

---

CHANGES.md
cratedb_sqlparse_js/tests/exceptions.test.js
cratedb_sqlparse_py/tests/test_exceptions.py

Add tests to check that special characters '\r, \n, \t'

---

CHANGES.md
cratedb_sqlparse_js/cratedb_sqlparse/index.js
cratedb_sqlparse_py/cratedb_sqlparse/__init__.py
setup_grammar.py

Set CrateDB version to 5.8.3

---

CHANGES.md
cratedb_sqlparse_js/cratedb_sqlparse/parser.js
cratedb_sqlparse_js/tests/exceptions.test.js
cratedb_sqlparse_py/cratedb_sqlparse/parser.py
cratedb_sqlparse_py/tests/test_exceptions.py

Changes how we heuristically match queries on missing error context.
Fixes #113

Improve error matching on missing EOF

---

.github/workflows/python.yml
cratedb_sqlparse_py/pyproject.toml

- [Chore: Format pyproject.toml using recent pyproject-fmt](https://github.com/crate/cratedb-sqlparse/commit/785afa4218b353c563961d84a9e331a0c6fee4d8)
- [CI: Validate on Python 3.13](https://github.com/crate/cratedb-sqlparse/commit/d499deed5734ec47d6eb38eb938346b2d7c77ca8)

Python: Just maintenance

---

cratedb_sqlparse_py/pyproject.toml
requirements.txt

[poethepoet](https://pypi.org/project/poethepoet/)'s standard interfaces are considered stable enough, so this patch intends to reduce future Dependabot traffic.
The patch will make those obsolete:
- GH-153
- GH-155
/cc @tomach, @Taliik, @juanpardo

Chore: Update to `poethepoet<1`

---

.github/workflows/javascript.yml
.github/workflows/python.yml
.github/workflows/release.yml
.github/workflows/release_javascript.yml
.github/workflows/release_python.yml
.gitignore
DEVELOP.md
README.md
cratedb_sqlparse_py/pyproject.toml
pyproject.toml
requirements.txt
setup_grammar.py

For a long time I was unhappy with how the setup of this project ended up being, it was prone to breaking and made maintenance annoying. I've simplified and improve things to address these issues:
* Remove CrateDB service from testing CI
* Update Python versions from 3.8, 3.13 to ["3.10", "3.11", "3.12", "3.13"]
* Use uv in project setup, CI and cratedb-sqlparse python parser
* Run only tests when library changes fixes #39 
* Update cratedb_sqlparse_py pyproject's metadata
* Update CrateDB version to 5.10.4
* Create new release pipeline for NPM package. fixes #115
* Unify release in a single workflow release.yml and make it trigger able by GitHub releases.
* Update both README and DEVELOP documentation

Over-haul of CI
